global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'erp-prod'

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-primary'

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: nginx
    static_configs:
      - targets: ['nginx:9113']

  # Uncomment after deploying node-exporter on the host
  # - job_name: node
  #   static_configs:
  #     - targets: ['host.docker.internal:9100']
